"""add icloud_uid and target to scheduled_tasks

Revision ID: 53eba8db08bf
Revises: 
Create Date: 2026-02-24 19:10:14.666621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53eba8db08bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_verses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('ayah_start', sa.Integer(), nullable=False),
    sa.Column('ayah_end', sa.Integer(), nullable=False),
    sa.Column('text_arabic', sa.Text(), nullable=False),
    sa.Column('text_translation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_verses_date'), 'daily_verses', ['date'], unique=False)
    op.create_index(op.f('ix_daily_verses_telegram_id'), 'daily_verses', ['telegram_id'], unique=False)
    op.add_column('scheduled_tasks', sa.Column('icloud_uid', sa.String(length=255), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('target', sa.String(length=20), server_default='reminder', nullable=False))
    op.add_column('users', sa.Column('apple_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('apple_app_password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'apple_app_password')
    op.drop_column('users', 'apple_id')
    op.drop_column('scheduled_tasks', 'target')
    op.drop_column('scheduled_tasks', 'icloud_uid')
    op.drop_index(op.f('ix_daily_verses_telegram_id'), table_name='daily_verses')
    op.drop_index(op.f('ix_daily_verses_date'), table_name='daily_verses')
    op.drop_table('daily_verses')
    # ### end Alembic commands ###
